name: Build & Deploy

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/adriaandot/circle.adriaan.com:latest,ghcr.io/adriaandot/circle.adriaan.com:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_REV=${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy
        env:
          DEPLOY_SSH_KEY: "${{ secrets.DEPLOY_SSH_KEY }}"
          KNOWN_HOSTS: "circle.adriaan.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFHooiVfZDGg5ubm2UIUyFbvHpKukl11bp1ueKSUnQep"
        run: |
          mkdir -p ~/.ssh
          echo "$KNOWN_HOSTS" >> ~/.ssh/known_hosts
          echo "$DEPLOY_SSH_KEY" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key
          ssh -i /tmp/ssh_key -T adriaan@circle.adriaan.com
